# Generated by Django 4.2.30 on 2026-04-27 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("question_bank", "0003_add_course_mindmap_pdf"),
    ]

    operations = [
        migrations.CreateModel(
            name="WrongQuestionReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_wrong_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="第一次做错时间"
                    ),
                ),
                (
                    "last_review_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最近一次复习时间"
                    ),
                ),
                (
                    "review_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="已正确复习次数"
                    ),
                ),
                ("next_review_time", models.DateTimeField(verbose_name="下次复习时间")),
                (
                    "is_mastered",
                    models.BooleanField(default=False, verbose_name="是否已掌握"),
                ),
                (
                    "is_removed",
                    models.BooleanField(
                        default=False, verbose_name="是否从复习计划移除"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_records",
                        to="question_bank.question",
                        verbose_name="题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_question_reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "错题复习记录",
                "verbose_name_plural": "错题复习记录",
                "db_table": "wrong_question_reviews",
                "ordering": ["next_review_time"],
            },
        ),
        migrations.AddConstraint(
            model_name="wrongquestionreview",
            constraint=models.UniqueConstraint(
                fields=("user", "question"), name="unique_user_question_review"
            ),
        ),
    ]
