# Generated by Django 6.0.4 on 2026-04-22 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("question_bank", "0002_alter_question_options_question_business_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FavoriteQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_records",
                        to="question_bank.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏记录",
                "verbose_name_plural": "收藏记录",
                "db_table": "favorite_questions",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "question"),
                        name="unique_user_favorite_question",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WrongQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "wrong_count",
                    models.PositiveIntegerField(default=1, verbose_name="累计错误次数"),
                ),
                (
                    "last_wrong_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="最近一次答错时间"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="是否保留在错题本中"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_records",
                        to="question_bank.question",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wrong_questions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "错题记录",
                "verbose_name_plural": "错题记录",
                "db_table": "wrong_questions",
                "ordering": ["-last_wrong_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "question"), name="unique_user_wrong_question"
                    )
                ],
            },
        ),
    ]
