# Generated by Django 6.0.4 on 2026-04-22 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("question_bank", "0002_alter_question_options_question_business_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PracticeSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_count",
                    models.PositiveIntegerField(default=0, verbose_name="题目总数"),
                ),
                (
                    "answered_count",
                    models.PositiveIntegerField(default=0, verbose_name="已答数量"),
                ),
                (
                    "correct_count",
                    models.PositiveIntegerField(default=0, verbose_name="正确数量"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("in_progress", "进行中"), ("finished", "已完成")],
                        default="in_progress",
                        max_length=20,
                        verbose_name="会话状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="开始时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "subchapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to="question_bank.subchapter",
                        verbose_name="所属子章节",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_sessions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "练习会话",
                "verbose_name_plural": "练习会话",
                "db_table": "practice_session",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="PracticeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_answer",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="用户答案"
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(blank=True, null=True, verbose_name="是否正确"),
                ),
                (
                    "is_answered",
                    models.BooleanField(default=False, verbose_name="是否已作答"),
                ),
                (
                    "answer_mode",
                    models.CharField(
                        choices=[
                            ("single_choice", "单选题作答"),
                            ("big_question_viewed", "大题已查看"),
                        ],
                        default="single_choice",
                        max_length=30,
                        verbose_name="作答方式",
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作答时间"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_records",
                        to="question_bank.question",
                        verbose_name="题目",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="practice.practicesession",
                        verbose_name="所属练习会话",
                    ),
                ),
            ],
            options={
                "verbose_name": "练习记录",
                "verbose_name_plural": "练习记录",
                "db_table": "practice_record",
                "ordering": ["session", "question__order_no"],
            },
        ),
        migrations.AddIndex(
            model_name="practicesession",
            index=models.Index(
                fields=["user", "status"], name="practice_se_user_id_30c788_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practicesession",
            index=models.Index(
                fields=["user", "subchapter"], name="practice_se_user_id_56a303_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practicerecord",
            index=models.Index(
                fields=["user", "question"], name="practice_re_user_id_ea46a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="practicerecord",
            index=models.Index(
                fields=["session", "question"], name="practice_re_session_8a9920_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="practicerecord",
            constraint=models.UniqueConstraint(
                fields=("session", "question"), name="unique_session_question_record"
            ),
        ),
    ]
