# Generated by Django 6.0.4 on 2026-04-24 06:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practice", "0001_init_practice_models"),
        ("question_bank", "0003_add_course_mindmap_pdf"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubchapterPracticeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unattempted", "未作答"),
                            ("correct", "正确"),
                            ("wrong", "错误"),
                        ],
                        default="unattempted",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "first_answer",
                    models.CharField(
                        blank=True, max_length=1, null=True, verbose_name="首次答案"
                    ),
                ),
                (
                    "is_locked",
                    models.BooleanField(
                        default=False, verbose_name="是否锁定（锁定后不允许再覆盖）"
                    ),
                ),
                (
                    "first_answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="首次作答时间"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_progresses",
                        to="question_bank.question",
                        verbose_name="题目",
                    ),
                ),
                (
                    "subchapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_progresses",
                        to="question_bank.subchapter",
                        verbose_name="所属子章节",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_progresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "子章节刷题进度",
                "verbose_name_plural": "子章节刷题进度",
                "db_table": "subchapter_practice_progress",
                "indexes": [
                    models.Index(
                        fields=["user", "subchapter"],
                        name="subchapter__user_id_1a6c1f_idx",
                    ),
                    models.Index(
                        fields=["user", "subchapter", "status"],
                        name="subchapter__user_id_f5cbfd_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "subchapter", "question"),
                        name="unique_user_subchapter_question_progress",
                    )
                ],
            },
        ),
    ]
