# Generated by Django 6.0.4 on 2026-04-16 12:02

import apps.question_bank.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.PositiveIntegerField(
                        default=0, unique=True, verbose_name="顺序号"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="课程名称")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "db_table": "question_bank_course",
                "ordering": ["order_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.PositiveIntegerField(default=0, verbose_name="顺序号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="章节名称")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="question_bank.course",
                        verbose_name="所属课程",
                    ),
                ),
            ],
            options={
                "verbose_name": "章节",
                "verbose_name_plural": "章节",
                "db_table": "question_bank_chapter",
                "ordering": ["order_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="SubChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.PositiveIntegerField(default=0, verbose_name="顺序号"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="子章节名称")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subchapters",
                        to="question_bank.chapter",
                        verbose_name="所属章节",
                    ),
                ),
            ],
            options={
                "verbose_name": "子章节",
                "verbose_name_plural": "子章节",
                "db_table": "question_bank_subchapter",
                "ordering": ["order_no", "id"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_no",
                    models.PositiveIntegerField(default=0, verbose_name="顺序号"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[("single_choice", "单选题"), ("big_question", "大题")],
                        default="single_choice",
                        max_length=20,
                        verbose_name="题目类型",
                    ),
                ),
                (
                    "stem_text",
                    models.TextField(blank=True, null=True, verbose_name="题干文本"),
                ),
                (
                    "stem_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.question_bank.models.question_stem_upload_to,
                        verbose_name="题干图片",
                    ),
                ),
                (
                    "option_a_text",
                    models.TextField(blank=True, null=True, verbose_name="选项A文本"),
                ),
                (
                    "option_a_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.question_bank.models.question_option_upload_to,
                        verbose_name="选项A图片",
                    ),
                ),
                (
                    "option_b_text",
                    models.TextField(blank=True, null=True, verbose_name="选项B文本"),
                ),
                (
                    "option_b_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.question_bank.models.question_option_upload_to,
                        verbose_name="选项B图片",
                    ),
                ),
                (
                    "option_c_text",
                    models.TextField(blank=True, null=True, verbose_name="选项C文本"),
                ),
                (
                    "option_c_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.question_bank.models.question_option_upload_to,
                        verbose_name="选项C图片",
                    ),
                ),
                (
                    "option_d_text",
                    models.TextField(blank=True, null=True, verbose_name="选项D文本"),
                ),
                (
                    "option_d_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.question_bank.models.question_option_upload_to,
                        verbose_name="选项D图片",
                    ),
                ),
                (
                    "correct_answer",
                    models.CharField(
                        blank=True,
                        choices=[("A", "A"), ("B", "B"), ("C", "C"), ("D", "D")],
                        max_length=1,
                        null=True,
                        verbose_name="正确答案",
                    ),
                ),
                (
                    "analysis_text",
                    models.TextField(blank=True, null=True, verbose_name="解析文本"),
                ),
                (
                    "analysis_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.question_bank.models.question_analysis_upload_to,
                        verbose_name="解析图片",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "subchapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="question_bank.subchapter",
                        verbose_name="所属子章节",
                    ),
                ),
            ],
            options={
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
                "db_table": "question_bank_question",
                "ordering": ["order_no", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("course", "order_no"), name="unique_course_order_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="chapter",
            constraint=models.UniqueConstraint(
                fields=("course", "name"), name="unique_course_chapter"
            ),
        ),
        migrations.AddConstraint(
            model_name="subchapter",
            constraint=models.UniqueConstraint(
                fields=("chapter", "order_no"), name="unique_chapter_order_no"
            ),
        ),
        migrations.AddConstraint(
            model_name="subchapter",
            constraint=models.UniqueConstraint(
                fields=("chapter", "name"), name="unique_chapter_subchapter"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                fields=("subchapter", "order_no"), name="unique_subchapter_order_no"
            ),
        ),
    ]
