# Generated by Django 6.0.4 on 2026-04-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_bank", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="question",
            options={
                "ordering": ["subchapter", "order_no", "id"],
                "verbose_name": "题目",
                "verbose_name_plural": "题目",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="business_id",
            field=models.CharField(
                blank=True,
                help_text="10位固定编号：课程(2)+章节(2)+子章节(2)+题目(4)",
                max_length=10,
                verbose_name="业务编号",
            ),
        ),
    ]
