# Generated by Django 6.0.4 on 2026-04-23 05:28

import apps.question_bank.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("question_bank", "0002_alter_question_options_question_business_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="mindmap_pdf",
            field=models.FileField(
                blank=True,
                help_text="上传该课程的思维导图 PDF 文件",
                null=True,
                upload_to=apps.question_bank.models.course_mindmap_upload_to,
                verbose_name="思维导图 PDF",
            ),
        ),
    ]
